### ISSUE TITLE
(3.0.53) test class not defined in package shows up in package of SUnit browser

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#378]
![image](https://user-images.githubusercontent.com/623951/50523731-93053c00-0a86-11e9-97f7-e412f2d504f2.png)
I don't expect RwRowanProjectIssuesTest to show up in the Rowan-Services-Tests package ... I would think that only classes defined in the test package should show up in any one package....

If you are going to include classes with extension methods from the package, then the class name should be highlighted like it is in the project browser ... and then only the extension test methods should be listed ...

Overall I think there would be less confusion if the SUnit browser only displayed the test classes that are defined in the selected package ..

**Comment by ericwinger** [comment]
Fix entirely in Rowan oscar branch https://github.com/GemTalk/Rowan/commit/a962ffe0c7891d96ed4b439a4b9d521884dbb9cc

**Comment by LisaAlmarode** [comment]
While the tests aren't shown in the package... 

Why is the package with only extension test methods in the list in the SUnit browser in the first place?  

The Sunit browser only lists packages with classes that have test methods.  So it's not correct to include any package that has an empty set of classes.

**Comment by ericwinger** [comment]
> The Sunit browser only lists packages with classes that have test methods. So it's not correct to include any package that has an empty set of classes.

@LisaAlmarode I'm not seeing this. 

![image](https://user-images.githubusercontent.com/36212516/62661055-b8afc900-b924-11e9-8691-217f95b8c147.png)

**Comment by LisaAlmarode** [comment]
Did you try it with the specific case that is described in this bug?   

The problem is pretty clearly related to having an extension method in this other package.  

![image](https://user-images.githubusercontent.com/13142166/62663431-44792380-b92c-11e9-8b95-9e6f89f2f726.png)

**Comment by ericwinger** [comment]
Hmmm, maybe I'm missing something obvious but I don't see the problem in this picture. 
![image](https://user-images.githubusercontent.com/36212516/62665074-c66c4b00-b932-11e9-8e46-2da86fef6bcf.png)

**Comment by LisaAlmarode** [comment]
Notice that there are no methods?  You have to actually have an extension test method defined before the package shows up in the SUnit browser. 

Create an instance method named test_test, on the class RowanSample1Test but in the RowanSample1-Extensions package.  I expect then you will see the RowanSample1-Extensions package show up in the left pane of the Sunit browser.

**Comment by ericwinger** [comment]
I think I see the bug. If a test method is in an extension package and the test class has no other tests, the sunit browser does not show the test. 

![image](https://user-images.githubusercontent.com/36212516/62732438-2ddcd600-b9d9-11e9-834c-f423062c66a4.png)

**Comment by ericwinger** [comment]
Fixed in Oscar 3.0.75. (Actual fix in Oscar branch of Rowan project).  ``RowanPackageService>>testClasses`` was not accounting for test classes defined in the package correctly when only extension methods were present.

**Comment by LisaAlmarode** [comment]
Still the same behavior in 3.0.75.

**Comment by ericwinger** [comment]
Although this commit https://github.com/GemTalk/Jadeite/issues/378#issuecomment-521823530 fixed one aspect of the problem, it became apparent that extension tests caused problems in the sunit browser as it is currently designed. Example - If you had a test class with test methods only defined in an extension package, to see it you would have to show the extension package in the list. But, if you added a second test method in the defined package of the test class, it would "jump" to the other package. That wasn't very desirable. 

In order to better handle situations like these, I changed the behavior of the sunit browser to show extensions. Test extension packages will appear if tests are defined in them. Extension classes and test methods will appear in purple now similar to the project browser. If you select the test class in either the package it was defined in or in an extension package, you will still see the entire list of tests. 

In addition, the sunit browser does a better job updating itself after changes in other browsers.

**Comment by LisaAlmarode** [comment]
Testing in 3.0.77 

 - [ ]  When I have the sunit browser showing the full set of test run results, and I also have a PB open, and I change from classes view to hierarchy view, I lose all my test result icons, but the upper red bar still shows the summary of test results.  
First, I don't want to lose my results since I was trying to find the actual method that got the error.  Second, if you clear the icons seems like the results bar should also always be cleared.

- [ ] The order of the tests is not matching between Sunit browser and the sunit tab.  The underbar sorts after characters in the sunit tab, and before in the sunit browser.

- [ ]  adding/removing tests in PB in superclasses, doesn't update list in sunit browser.  I've got some abstract superclasses of my test classes.  If I'm looking at my concrete class tests in the sunit browser, and I add or remove a test method to/from the superclass, the tests don't get updated in the sunit browser. In fact after removing a method in the PB, I can run tests in Sunit browser (the removed method shows up as a test error).  Once I select that exact class in the PB (not a superclass), the Sunit browser finally updates.

--------------

Other comments:

With this change, for classes with test methods in two packages, the full set of test methods appear in two places, under each package.  The highlighting appears correct.  This matches the Sunit browser and seems reasonable.

As far as I can remember, the stickiness of test results in the Sunit browser has been much reduced since ancient days, but this seems like a good thing.

**Comment by LisaAlmarode** [comment]
This issue is related to inherited test methods as well as extensions, which I'm fairly sure have many holes, but I think is an unrealistic end-2022 goal.
