### ISSUE TITLE
Sunit confused by multiple Sunit tabs in project browser

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#419]
I have an SUnit browser open. and a project browser that has two project tabs.  Both project tabs are on test classes, different test classes, and both are on their respective SUnit tabs.

The PB tab #1 sunit tab makes the SUnit browser update in sync, which is nice.

If I go to PB tab #2, with a different test class selected, and run the test - that updates the SUnit Browser test results, except that it's the wrong class!  The same comedy of errors occurs between tabs too; if the method name matches, things get updated without regard to the selected class.

**Comment by LisaAlmarode** [comment]
![image](https://user-images.githubusercontent.com/13142166/51869472-7c603800-2305-11e9-944f-4e7500d00f84.png)

**Comment by ericwinger** [comment]
@LisaAlmarode - I'm having trouble reproducing this either running the test from the SUnit tab or SUnit browser. I can't find the version you're using in the information provided. Does this reproduce with 3.0.60?

**Comment by LisaAlmarode** [comment]
It's in 3.0.60, but it turns out to be specific to inherited tests.

To reproduce, load RowanSample1 and create a subclass of RowanSample1Test, mine is named RowanSample1TestSubclass.  Don't create any methods.  

In the Project Browser, select RowanSample1TestSubclass and the SUnit tab - it will show all the inherited tests. 
In the SUnit browser, select the superclass, RowanSample1Test, which shows the same set of tests.
Run tests on RowanSample1TestSubclass in the Project browser.
See the icons for the superclass, RowanSample1Test, update in the Sunit browser.

In my code, while the test methods are inherited, they call other methods that are overridden in the subclass, which causes the tests to be run on the client or server, so while the same test methods run the test results are completely unrelated.  My screen shot shows OrderPricerTester which is a sibling class of PlantiUnixTester, they are both subclasses of PlantisTester which implements those four methods

**Comment by ericwinger** [comment]
Believe I've got this fixed in 3.0.63. Added tests in https://github.com/GemTalk/Jadeite/commit/0de131a5b81d77ba1a4097ee09478019c49bfc76
Fix in https://github.com/GemTalk/Jadeite/commit/db74b81816651a8d4e557f2ec98024b4a8194973

**Comment by LisaAlmarode** [comment]
The SUnit case is fixed but the Project browser remains.  The list of icons can be displayed for the superclass even though tests were not run on the superclass and would fail if they were run.

If you've got two project browsers.  
One is on the subclass and has run tests and shows all the icons (passing)
In the other project browser, select the superclass, that actually implements the tests and which fail (bad code in support method that is overriden in subclass).

The superclass show all the same test-result icons even though no tests have been run and if they had been run the results would be different.  this is incorrect.

Run tests on the superclass, so you see all the red Xs.

Then in the other browser, that had previously selected the subclass, select the superclass (the one that is full of red Xes in the other browser). This shows the subclass results from the same browser, and does NOT show the results for the superclass displayed in the other browser.

**Comment by ericwinger** [comment]
> The superclass show all the same test-result icons even though no tests have been run and if they had been run the results would be different. this is incorrect.

@LisaAlmarode I'm not seeing this behavior. Instead I see no test results from selecting the super class. Is it possible you were testing with a version prior to 3.0.63?

**Comment by LisaAlmarode** [comment]
Still happens in 3.0.64.  It occurs when the methods are inherited, not defined in the subclass.  It's a peculiar scenario.

in subclass, run the tests.  Note that there are no test methods in this class.

![image](https://user-images.githubusercontent.com/13142166/53376659-f6d7a400-3913-11e9-95ce-27cf6e4d04e0.png)

Now, select its superclass, then select the sunit tab.  See icons:

![image](https://user-images.githubusercontent.com/13142166/53376672-ffc87580-3913-11e9-81a9-170387f0ea6e.png)

Note that it looks like tests were run and passed. However, if you run tests in the superclass, they fail (expected, I broke the file separator):

![image](https://user-images.githubusercontent.com/13142166/53376677-0820b080-3914-11e9-8edf-8f1554a37fcc.png)

**Comment by dalehenrich** [comment]
agree that it is a peculiar scenario ... in this particular case the fact that the tests are behaving correctly in the concrete test is most important to get right at this stage

**Comment by LisaAlmarode** [comment]
In my test code, both are concrete classes; the superclass runs the same tests on windows and is the important one.  The subclass was added just for Jadeite testing so I could run tests on unix, since the windows tests take so long.  The difference is that the subclass overrides a few methods that setup files and directories. 

I removed the labels since I'm guessing this isn't in scope for this week, but tests are not behaving correctly in one of the concrete test classes...

**Comment by LisaAlmarode** [comment]
The final issue here is still behaving incorrectly in 3.0.75.  Probably need to close this issue and open a new one specific to inherited test cases.

**Comment by ericwinger** [comment]
@LisaAlmarode Perhaps I've lost the thread but in my simple tests, I'm seeing the correct test results. Can you file a new bug with the reproduction case?  Here is my "reproduction case":

- define new method in ``RowanSample1Test``
```
test_failInConcreteClass

	self assert: self class name equals: #SubTest
```
- Create Subclass of ``RowanSample1Test`` called ``SubTest``
- test passes when run in SubTest (as expected)
![image](https://user-images.githubusercontent.com/36212516/63725449-302f9480-c80f-11e9-99b9-1a1456e61676.png)
- test fails when run in concrete class (as expected)
![image](https://user-images.githubusercontent.com/36212516/63725511-6ec54f00-c80f-11e9-9f34-1a8ad57ea387.png)

**Comment by LisaAlmarode** [comment]
Filed issue #526 with simple and detailed reproduction case, see the WRONG for what the issue is.
