### ISSUE TITLE
(3.0.87) Extra click after logout to reenable the login button

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#635]
- Login to Jadeite
- Logout
- Login button is disabled.
- Click on Login window somewhere.
- Login button becomes enabled. 

Need to eliminate need for extra click.

**Comment by ericwinger** [comment]
Fixed in 3.0.88

**Comment by LisaAlmarode** [comment]
About one time in 10 or so, the login button doesn't re-enable by itself. However, I haven't yet been able to make it happen on purpose. When I try to setup complicated sets of windows to trigger the not-reenablement... it very reliably works correctly. So reopening, but leaving assigned to myself.

**Comment by ericwinger** [comment]
Took another look at this. Think I found a more deterministic fix which seems to work better. Needs further retesting.

**Comment by LisaAlmarode** [comment]
Still occurs about the same frequency and equally only after some time of doing stuff and not reproducible.

**Comment by ericwinger** [comment]
Have an improved fix. The button's enablement seems to be influenced by what window has focus. If the login window does not have focus, logging out wouldn't enable the login button. Force the login window to have focus before invalidating the button.

**Comment by LisaAlmarode** [comment]
Haven't seen this, I don't think, so (tentatively) agree it's fixed.
