### ISSUE TITLE
make autocomplete case insensitive

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#636]
Customer has requested that autocomplete be case insensitive. Example below. 

![image](https://user-images.githubusercontent.com/36212516/68966858-eca45100-0793-11ea-941b-68445143789f.png)
![image](https://user-images.githubusercontent.com/36212516/68966874-f1690500-0793-11ea-9da9-56a7876d2dd5.png)

**Comment by ericwinger** [comment]
Fixed in 3.0.88. Made insensitive & fixed a bug. MS CRT specified sort needed to make scintilla autocomplete work as expected.

**Comment by LisaAlmarode** [comment]
Features seems not quite complete, since the list of found selectors is sorted by case.... could be very hard to find what you're looking for.

![image](https://user-images.githubusercontent.com/13142166/69107001-ea0c5a80-0a24-11ea-9e61-5c9ae47fa57a.png)

**Comment by dalehenrich** [comment]
If you're going to fiddle with sorting, please see if #622 would be a better approach ... it seems that sorting by match length with shortest matches first would address @LisaAlmarode issue, since the `lowercase` entries that differ only be case would be at the top of the list ... don't you think?

**Comment by ericwinger** [comment]
@LisaAlmarode - What's your thoughts on Dale's proposal to skip alphabetic sorting in favor a pure size sort with shortest first? 

Note - Sort may be a mute point because the underlying MS function call which builds the autocomplete window acts oddly with different sort orders. i.e. I may not be able to change sort order and still use this autocomplete feature as is. Rolling my own would take a bit of time.

**Comment by LisaAlmarode** [comment]
I'm not using this feature in practice, and I think it's the kind of thing you'd need to use for a while, to really know what would be better - so I'm fine trying Dale's from-the-field approach.  

Hmm.  You'd still face the case issue, although not as badly.   E.g., if we add lowerCaseLatin and lowercaseLatin and lowerCASELatin, the same length strings as the *Greek methods.... it would matter.

**Comment by ericwinger** [comment]
You can ignore my [note](https://github.com/GemTalk/Jadeite/issues/636#issuecomment-555650923). I think I got ignore case figured out. https://www.scintilla.org/ScintillaDoc.html#SCI_AUTOCSHOW

Before I implement "shortest first sort" here is an example of how it might look without alphabetization.
Is this ok @dalehenrich @LisaAlmarode ? 
![image](https://user-images.githubusercontent.com/36212516/69177250-00192a00-0abc-11ea-8130-b78f5f92521b.png)

**Comment by LisaAlmarode** [comment]
One could make a point that if you've typed in a capital C then you might want to see the matches that case-match what you typed, before the ones that don't. However, can of worms here.

**Comment by ericwinger** [comment]
To do that, we'd have to conditionally turn on case sensitivity whenever a capital was detected in the string. Not sure that's the customer's intent.  Closing as fixed in 3.0.88 and ready for review.

**Comment by LisaAlmarode** [comment]
Side note: turns out autocomplete expected initial-lowercase to a method (not, for example, allowing you to enter One_water or Water_one methods, mentioned in another issue), and it treats any initial-uppercase typing as a class name. 

Method case insenitive seem solid.

However: Class names are not searched class-insensitive.  

I have a lot of classnames that start with MAV.
When I type in MA I see them. But not with Ma.

![image](https://user-images.githubusercontent.com/13142166/69208545-ca4e6280-0b08-11ea-9f19-972b31b5b765.png)

![image](https://user-images.githubusercontent.com/13142166/69208529-c0c4fa80-0b08-11ea-9449-655419e36c44.png)

**Comment by LisaAlmarode** [comment]
Verified that class autocomplete **is** case sensitive in 3.0.91.

**Comment by LisaAlmarode** [comment]
Created issue #660 for just the class case sensitivity.  Closing this issue.
