### ISSUE TITLE
Wildcard method search broken if autcomplete off (3.0.93-6)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#732]
Searching for implementors of... with a trailing * returns an empty dialog if you have autocomplete disabled (which I always do). 

Turning autocomplete on so it cached the symbols allows the method to be found, so there's a workaround.

Need to add that wild card lookup is supported to the users guide - I couldn't remember if this was supported although it seemed obviously necessary.

**Comment by ericwinger** [comment]
Fixed in Oscar 3.1.0. Needed to add a new path if symbols aren't cached.

**Comment by LisaAlmarode** [comment]
No change, not working in prerelease 2; with autocomplete off, the list is empty for Browse Implementors of... on postLoad* (while e.g. Browse Implementors of... on postLoadOver: returns two methods).

**Comment by ericwinger** [comment]
I'm not seeing the problem after I did some more work in this area for #669 in pre-release3. Please review again when that is released.

**Comment by LisaAlmarode** [comment]
Eric, did you try the specific example with postLoad*?  Still no improvement in pr3.

**Comment by ericwinger** [comment]
Yes, this is what I see after starting Dolphin & loading Jadeite without touching the auto complete menu item or doing anything else. 

![image](https://user-images.githubusercontent.com/36212516/78843289-3dbd1780-79b7-11ea-8935-e0edd28ee29a.png)

**Comment by LisaAlmarode** [comment]
I'm glad you see that list but it doesn't help me...

**Comment by ericwinger** [comment]
Found the problem. When a new method is compiled, the symbols are added to the client's autocomplete cache of symbols so that the user can find those symbols without recaching all symbols. This was still being done even if autocomplete was off. The code path that was searching for matching selectors was asking the all symbols cache if it was empty (which it wasn't if a method had been compiled.) Since it wasn't, it searched the tiny set of symbols from that method. 

That's been fixed in 3.1.0pre-release4. To test,
- Start Jadeite
- don't turn on autocomplete. 
- search for implementors of `postLo*` 
- see proper list
- compile method
- search for implementors of `postLo*`
- should still see proper list.

**Comment by LisaAlmarode** [comment]
I still see an empty list in PR4 when I search for implementors of postLo* or postLoad*.

**Comment by ericwinger** [comment]
New code didn't handle cases correctly. Fixed in 3.1.0pre-release5.
